# Generated by Antigen. Do not edit!
function git_branch_name() {
  branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
  if [[ $branch == "" ]];
  then
    :
  else
    echo '%F{32}('$branch')%f '
  fi
}


PROMPT='%B%F{blue}[%f%F{yellow}%n%f%F{white}:%f%F{green}%~%f%F{blue}]%f $(git_branch_name)%F{red}λ%f%b '
