#!/usr/bin/sh

sxhkd &
picom --config /home/zilq/.config/picom/picom.conf &
feh --bg-fill /home/zilq/Downloads/wallhaven-lmxmxy.png &
xsetroot -cursor_name left_ptr &
setxkbmap -option grp:win_space_toggle us,ee,ru &
redshift &
polybar &

bspc monitor -d      

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#ff9e64"
