#!/usr/bin/sh

sxhkd &
picom --config /home/zilq/.config/picom/picom.conf &
polybar main &

#bspc wm --reorder-monitors DisplayPort-0 HDMI-A-0 DisplayPort-1
bspc monitor DisplayPort-0 -d 2
bspc monitor DisplayPort-1 -d 1
bspc monitor HDMI-A-1 -d 3 4

bspc config border_width         4
bspc config window_gap          30

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#fec43f"
bspc config active_border_color "#606060"
bspc config normal_border_color "#606060"

bspc rule -a Bitwarden state=floating
bspc rule -a Steam state=floating
