local c = require("zq.theme.koda.palette")

local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()
    -- highlights
    hl(0, "Normal", { fg = c.base05, bg = c.base00 })
    hl(0, "SignColumn", { fg = c.base03, bg = c.statuscolumn, sp = "NONE" })
    hl(0, "MsgArea", { fg = c.base05, bg = c.base00 })
    hl(0, "ModeMsg", { fg = c.base0B, bg = "NONE" })
    hl(0, "MsgSeparator", { fg = c.base05, bg = c.base00 })
    hl(0, "SpellBad", { fg = "NONE", bg = "NONE", sp = c.base08, undercurl = true })
    hl(0, "SpellCap", { fg = "NONE", bg = "NONE", sp = c.base0D, undercurl = true })
    hl(0, "SpellLocal", { fg = "NONE", bg = "NONE", sp = c.base0C, undercurl = true })
    hl(0, "SpellRare", { fg = "NONE", bg = "NONE", sp = c.base0D, undercurl = true })
    hl(0, "NormalNC", { fg = c.base05, bg = c.base00 })
    hl(0, "Pmenu", { fg = "NONE", bg = "NONE" })
    hl(0, "PmenuSel", { bg = c.menu_select, fg = c.pmenu_bg })
    hl(0, "WildMenu", { fg = c.base08, bg = c.base0A })
    hl(0, "CursorLineNr", { fg = c.base05, bg = c.statuscolumn })
    hl(0, "CursorLineSign", { fg = c.white, bg = c.statuscolumn })
    hl(0, "Comment", { fg = c.grey_fg, bg = "NONE" })
    hl(0, "Folded", { fg = c.base03, bg = c.base01 })
    hl(0, "FoldColumn", { fg = c.base0C, bg = c.statuscolumn })
    hl(0, "LineNr", { fg = c.base04, bg = c.statuscolumn })
    hl(0, "VertSplit", { fg = c.line, bg = "NONE" })
    hl(0, "WinSeparator", { fg = c.line, bg = "NONE" })
    hl(0, "FloatBorder", { fg = c.grey_fg, bg = "NONE" })
    hl(0, "CursorLine", { fg = "NONE", bg = c.black2 })
    hl(0, "CursorColumn", { fg = "NONE", bg = c.statuscolumn })
    hl(0, "ColorColumn", { fg = "NONE", bg = c.statuscolumn })
    hl(0, "NormalFloat", { fg = "NONE", bg = c.darker_black })
    hl(0, "Visual", { fg = c.visual_line_fg, bg = c.visual_line })
    hl(0, "VisualNOS", { fg = c.base08, bg = "NONE" })
    hl(0, "WarningMsg", { fg = c.base08, bg = "NONE" })
    hl(0, "DiffAdd", { fg = c.vibrant_green, bg = "NONE" })
    hl(0, "DiffChange", { fg = c.blue, bg = "NONE" })
    hl(0, "DiffDelete", { fg = c.red, bg = "NONE" })
    hl(0, "QuickFixLine", { fg = "NONE", bg = c.base01, sp = "NONE" })
    hl(0, "PmenuSbar", { fg = "NONE", bg = c.one_bg })
    hl(0, "PmenuThumb", { fg = "NONE", bg = c.grey })
    hl(0, "MatchWord", { fg = c.white, bg = c.grey })
    hl(0, "MatchParen", { link = "MatchWord" })
    hl(0, "Cursor", { fg = c.base00, bg = c.base05 })
    hl(0, "Conceal", { fg = "NONE", bg = "NONE" })
    hl(0, "Directory", { fg = c.base0D, bg = "NONE" })
    hl(0, "SpecialKey", { fg = c.base03, bg = "NONE" })
    hl(0, "Title", { fg = c.base0D, bg = "NONE", sp = "NONE" })
    hl(0, "ErrorMsg", { fg = c.base08, bg = c.base00 })
    hl(0, "Search", { fg = c.base01, bg = c.base0A })
    hl(0, "IncSearch", { fg = c.base01, bg = c.base09 })
    hl(0, "Substitute", { fg = c.base01, bg = c.base0A, sp = "NONE" })
    hl(0, "MoreMsg", { fg = c.base0B, bg = "NONE" })
    hl(0, "Question", { fg = c.base0D, bg = "NONE" })
    hl(0, "NonText", { fg = c.base03, bg = "NONE" })
    -- hl(0, "Exception", { fg = c.base08, bg = "NONE" })
    -- hl(0, "Macro", { fg = c.base08, bg = "NONE" })
    -- hl(0, "Debug", { fg = c.base08, bg = "NONE" })
    -- hl(0, "Underlined", { fg = c.base0B, bg = "NONE" })
    -- hl(0, "Bold", { fg = "NONE", bg = "NONE", bold = true })
    -- hl(0, "Italic", { fg = "NONE", bg = "NONE", italic = true })
    -- hl(0, "Ignore", { fg = c.cyan, bg = c.base00, bold = true })
    -- hl(0, "Error", { fg = c.base00, bg = c.base08 })
    -- hl(0, "TabLine", { fg = c.light_grey, bg = c.line })
    -- hl(0, "TabLineSel", { fg = c.white, bg = c.line })
    -- hl(0, "TabLineFill", { fg = c.line, bg = c.line })

    -- markdown
    hl(0, "markdownBlockquote", { fg = c.green, bg = "NONE" })
    hl(0, "markdownCode", { fg = c.orange, bg = "NONE" })
    hl(0, "markdownCodeBlock", { fg = c.orange, bg = "NONE" })
    hl(0, "markdownCodeDelimiter", { fg = c.orange, bg = "NONE" })
    hl(0, "markdownH1", { fg = c.blue, bg = "NONE" })
    hl(0, "markdownH2", { fg = c.blue, bg = "NONE" })
    hl(0, "markdownH3", { fg = c.blue, bg = "NONE" })
    hl(0, "markdownH4", { fg = c.blue, bg = "NONE" })
    hl(0, "markdownH5", { fg = c.blue, bg = "NONE" })
    hl(0, "markdownH6", { fg = c.blue, bg = "NONE" })
    hl(0, "markdownHeadingDelimiter", { fg = c.blue, bg = "NONE" })
    hl(0, "markdownHeadingRule", { fg = c.base05, bg = "NONE", bold = true })
    hl(0, "markdownId", { fg = c.purple, bg = "NONE" })
    hl(0, "markdownIdDeclaration", { fg = c.blue, bg = "NONE" })
    hl(0, "markdownIdDelimiter", { fg = c.light_grey, bg = "NONE" })
    hl(0, "markdownLinkDelimiter", { fg = c.light_grey, bg = "NONE" })
    hl(0, "markdownBold", { fg = c.blue, bg = "NONE", bold = true })
    hl(0, "markdownItalic", { fg = "NONE", bg = "NONE", italic = true })
    hl(0, "markdownBoldItalic", { fg = c.yellow, bg = "NONE", bold = true, italic = true })
    hl(0, "markdownListMarker", { fg = c.blue, bg = "NONE" })
    hl(0, "markdownOrderedListMarker", { fg = c.blue, bg = "NONE" })
    hl(0, "markdownRule", { fg = c.base01, bg = "NONE" })
    hl(0, "markdownUrl", { fg = c.cyan, bg = "NONE", underline = true })
    hl(0, "markdownLinkText", { fg = c.blue, bg = "NONE" })
    hl(0, "markdownFootnote", { fg = c.orange, bg = "NONE" })
    hl(0, "markdownFootnoteDefinition", { fg = c.orange, bg = "NONE" })
    hl(0, "markdownEscape", { fg = c.yellow, bg = "NONE" })

    -- Telescope
    -- hl(0, "TelescopeNormal", { fg = "NONE", bg = c.darker_black })
    hl(0, "TelescopeNormal", { fg = "NONE", bg = "NONE" })
    hl(0, "TelescopePreviewTitle", { fg = c.black, bg = c.green, bold = true })
    hl(0, "TelescopePromptTitle", { fg = c.black, bg = c.red, bold = true })
    hl(0, "TelescopeResultsTitle", { fg = c.white, bg = c.darker_black, bold = true })
    hl(0, "TelescopeSelection", { fg = c.white, bg = c.black2 })
    hl(0, "TelescopeBorder", { fg = c.grey, bg = "NONE" })
    hl(0, "TelescopePromptBorder", { fg = c.grey, bg = "NONE" })
    hl(0, "TelescopePromptNormal", { fg = c.white, bg = "NONE" })
    hl(0, "TelescopePromptPrefix", { fg = c.red, bg = c.black2 })
    hl(0, "TelescopeResultsDiffAdd", { fg = c.green, bg = "NONE" })
    hl(0, "TelescopeResultsDiffChange", { fg = c.blue, bg = "NONE" })
    hl(0, "TelescopeResultsDiffDelete", { fg = c.red, bg = "NONE" })

    -- NvimTree
    hl(0, "NvimTreeFolderIcon", { fg = c.blue, bg = "NONE" })
    hl(0, "NvimTreeIndentMarker", { fg = "#c5c5c5", bg = "NONE" })
    hl(0, "NvimTreeNormal", { fg = "NONE", bg = c.darker_black })
    hl(0, "NvimTreeVertSplit", { fg = c.darker_black, bg = c.darker_black })
    hl(0, "NvimTreeFolderName", { fg = c.blue, bg = "NONE" })
    hl(0, "NvimTreeOpenedFolderName", { fg = c.blue, bg = "NONE", bold = true, italic = true })
    hl(0, "NvimTreeEmptyFolderName", { fg = c.grey, bg = "NONE", italic = true })
    hl(0, "NvimTreeGitIgnored", { fg = c.grey, bg = "NONE", italic = true })
    hl(0, "NvimTreeImageFile", { fg = c.light_grey, bg = "NONE" })
    hl(0, "NvimTreeSpecialFile", { fg = c.orange, bg = "NONE" })
    hl(0, "NvimTreeEndOfBuffer", { fg = c.darker_black, bg = "NONE" })
    hl(0, "NvimTreeCursorLine", { fg = "NONE", bg = "#282b37" })
    hl(0, "NvimTreeGitignoreIcon", { fg = c.red, bg = "NONE" })
    hl(0, "NvimTreeGitStaged", { fg = c.vibrant_green, bg = "NONE" })
    hl(0, "NvimTreeGitNew", { fg = c.vibrant_green, bg = "NONE" })
    hl(0, "NvimTreeGitRenamed", { fg = c.vibrant_green, bg = "NONE" })
    hl(0, "NvimTreeGitDeleted", { fg = c.red, bg = "NONE" })
    hl(0, "NvimTreeGitMerge", { fg = c.blue, bg = "NONE" })
    hl(0, "NvimTreeGitDirty", { fg = c.blue, bg = "NONE" })
    hl(0, "NvimTreeSymlink", { fg = c.cyan, bg = "NONE" })
    hl(0, "NvimTreeRootFolder", { fg = c.base05, bg = "NONE", bold = true })
    hl(0, "NvimTreeExecFile", { fg = c.green, bg = "NONE" })
    hl(0, "NvimTreeWinSeparator", { fg = c.one_bg2, bg = "NONE" })

    -- Buffer
    hl(0, "BufferCurrent", { fg = c.base05, bg = c.base00 })
    hl(0, "BufferCurrentIndex", { fg = c.base05, bg = c.base00 })
    hl(0, "BufferCurrentMod", { fg = c.sun, bg = c.base00 })
    hl(0, "BufferCurrentSign", { fg = c.purple, bg = c.base00 })
    hl(0, "BufferCurrentTarget", { fg = c.red, bg = c.base00, bold = true })
    hl(0, "BufferVisible", { fg = c.base05, bg = c.base00 })
    hl(0, "BufferVisibleIndex", { fg = c.base05, bg = c.base00 })
    hl(0, "BufferVisibleMod", { fg = c.sun, bg = c.base00 })
    hl(0, "BufferVisibleSign", { fg = c.grey, bg = c.base00 })
    hl(0, "BufferVisibleTarget", { fg = c.red, bg = c.base00, bold = true })
    hl(0, "BufferInactive", { fg = c.grey, bg = c.darker_black })
    hl(0, "BufferInactiveIndex", { fg = c.grey, bg = c.darker_black })
    hl(0, "BufferInactiveMod", { fg = c.sun, bg = c.darker_black })
    hl(0, "BufferInactiveSign", { fg = c.grey, bg = c.darker_black })
    hl(0, "BufferInactiveTarget", { fg = c.red, bg = c.darker_black, bold = true })

    -- StatusLine
    hl(0, "StatusLine", { fg = c.line, bg = c.statusline_bg })
    hl(0, "StatusLineNC", { fg = "NONE", bg = c.statusline_bg })
    hl(0, "StatusLineSeparator", { fg = c.line, bg = "NONE" })
    hl(0, "StatusLineTerm", { fg = c.line, bg = "NONE" })
    hl(0, "StatusLineTermNC", { fg = c.line, bg = "NONE" })

    -- IndentBlankline
    hl(0, "IndentBlanklineContextChar", { fg = c.grey, bg = "NONE" })
    hl(0, "IndentBlanklineContextStart", { fg = "NONE", bg = c.one_bg2 })
    hl(0, "IndentBlanklineChar", { fg = c.line, bg = "NONE" })
    hl(0, "IndentBlanklineSpaceChar", { fg = c.line, bg = "NONE" })
    hl(0, "IndentBlanklineSpaceCharBlankline", { fg = c.sun, bg = "NONE" })

    -- Dashboard
    hl(0, "DashboardHeader", { fg = c.blue, bg = "NONE" })
    hl(0, "DashboardCenter", { fg = c.purple, bg = "NONE" })
    hl(0, "DashboardFooter", { fg = c.cyan, bg = "NONE" })

    -- Cmp
    hl(0, "CmpItemAbbrDeprecated", { fg = c.grey, bg = "NONE", strikethrough = true })
    hl(0, "CmpItemAbbrMatch", { fg = c.blue, bg = "NONE" })
    hl(0, "CmpItemAbbrMatchFuzzy", { fg = c.blue, bg = "NONE" })
    hl(0, "CmpItemKindFunction", { fg = c.blue, bg = "NONE" })
    hl(0, "CmpItemKindMethod", { fg = c.blue, bg = "NONE" })
    hl(0, "CmpItemKindConstructor", { fg = c.cyan, bg = "NONE" })
    hl(0, "CmpItemKindClass", { fg = c.cyan, bg = "NONE" })
    hl(0, "CmpItemKindEnum", { fg = c.cyan, bg = "NONE" })
    hl(0, "CmpItemKindEvent", { fg = c.yellow, bg = "NONE" })
    hl(0, "CmpItemKindInterface", { fg = c.cyan, bg = "NONE" })
    hl(0, "CmpItemKindStruct", { fg = c.cyan, bg = "NONE" })
    hl(0, "CmpItemKindVariable", { fg = c.red, bg = "NONE" })
    hl(0, "CmpItemKindField", { fg = c.red, bg = "NONE" })
    hl(0, "CmpItemKindProperty", { fg = c.red, bg = "NONE" })
    hl(0, "CmpItemKindEnumMember", { fg = c.orange, bg = "NONE" })
    hl(0, "CmpItemKindConstant", { fg = c.orange, bg = "NONE" })
    hl(0, "CmpItemKindKeyword", { fg = c.purple, bg = "NONE" })
    hl(0, "CmpItemKindModule", { fg = c.cyan, bg = "NONE" })
    hl(0, "CmpItemKindValue", { fg = c.base05, bg = "NONE" })
    hl(0, "CmpItemKindUnit", { fg = c.base05, bg = "NONE" })
    hl(0, "CmpItemKindText", { fg = c.base05, bg = "NONE" })
    hl(0, "CmpItemKindSnippet", { fg = c.yellow, bg = "NONE" })
    hl(0, "CmpItemKindFile", { fg = c.base05, bg = "NONE" })
    hl(0, "CmpItemKindFolder", { fg = c.base05, bg = "NONE" })
    hl(0, "CmpItemKindColor", { fg = c.base05, bg = "NONE" })
    hl(0, "CmpItemKindReference", { fg = c.base05, bg = "NONE" })
    hl(0, "CmpItemKindOperator", { fg = c.base05, bg = "NONE" })
    hl(0, "CmpItemKindTypeParameter", { fg = c.red, bg = "NONE" })
    hl(0, "CmpDocumentationBorder", { fg = "NONE", bg = "NONE" })

    -- ToggleTerm
    hl(0, "ToggleTerm1FloatBorder", { fg = c.line, bg = "NONE" })

    hl(0, "StatusColSep", { fg = c.line, bg = c.statuscolumn })
    hl(0, "StatusColSepMargin", { fg = "NONE", bg = c.black })
end

return theme
