local colors = require("zq.theme.monochrome.palette")

return {
	NavicIconsFile = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsModule = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsNamespace = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsPackage = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsClass = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsMethod = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsProperty = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsField = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsConstructor = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsEnum = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsInterface = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsFunction = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsVariable = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsConstant = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsString = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsNumber = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsBoolean = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsArray = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsObject = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsKey = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsNull = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsEnumMember = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsStruct = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsEvent = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsOperator = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicIconsTypeParameter = { bg = colors.navic_bg, fg = colors.navic_icon },
	NavicText = { bg = colors.navic_bg, fg = colors.navic_text },
	NavicSeparator = { bg = colors.navic_bg, fg = colors.navic_sep },
}
